### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/iacl/pg20/jacobr/calabresi/png/csv/train_png.csv'

### ISSUE THREAD

**Issue by HarshaSatyavardhan** [jcreinhold/counterfactualms#3]
when trying to reproduce the code I was getting this error. I tried to search the `'/iacl/pg20/jacobr/calabresi/png/csv/train_png.csv'` folder but unable to find It in the repository

```
GPU available: False, used: False
2023-02-24 11:07:00,828 - lightning - INFO - GPU available: False, used: False
TPU available: None, using: 0 TPU cores
2023-02-24 11:07:00,828 - lightning - INFO - TPU available: None, using: 0 TPU cores
Traceback (most recent call last):
  File "/content/counterfactualms/experiments/classifier/trainer.py", line 83, in <module>
    sys.exit(main())
  File "/content/counterfactualms/experiments/classifier/trainer.py", line 74, in main
    experiment = ClassifierExperiment(hparams)
  File "/usr/local/lib/python3.8/dist-packages/counterfactualms-0.0.1-py3.8.egg/counterfactualms/experiments/classifier/classifier_experiment.py", line 45, in __init__
    self.calabresi_train = CalabresiDataset(self.hparams.train_csv, crop_size=crop_size, crop_type=train_crop_type, resize=resize)  # noqa: E501
  File "/usr/local/lib/python3.8/dist-packages/counterfactualms-0.0.1-py3.8.egg/counterfactualms/datasets/calabresi.py", line 13, in __init__
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 814, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 1045, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 1862, in __init__
    self._open_handles(src, kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 1357, in _open_handles
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 639, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/iacl/pg20/jacobr/calabresi/png/csv/train_png.csv'
```

**Comment by jcreinhold** [comment]
The inclusion of that path in the code is a mistake. The training data isn't publicly available. If you want to use this model, you'll need to train it with your own data.
